import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        surface: "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-lowest": "var(--color-surface-container-lowest)",
        "surface-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-high": "var(--color-surface-container-high)",
        "surface-highest": "var(--color-surface-container-highest)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
      },
      fontSize: {
        "display-large": ["var(--typography-display-large-font-size)", {
          lineHeight: "var(--typography-display-large-line-height)",
          letterSpacing: "var(--typography-display-large-letter-spacing)",
          fontWeight: "var(--typography-display-large-font-weight)",
        }],
        "display-medium": ["var(--typography-display-medium-font-size)", {
          lineHeight: "var(--typography-display-medium-line-height)",
          letterSpacing: "var(--typography-display-medium-letter-spacing)",
          fontWeight: "var(--typography-display-medium-font-weight)",
        }],
        "display-small": ["var(--typography-display-small-font-size)", {
          lineHeight: "var(--typography-display-small-line-height)",
          letterSpacing: "var(--typography-display-small-letter-spacing)",
          fontWeight: "var(--typography-display-small-font-weight)",
        }],
        "headline-large": ["var(--typography-headline-large-font-size)", {
          lineHeight: "var(--typography-headline-large-line-height)",
          letterSpacing: "var(--typography-headline-large-letter-spacing)",
          fontWeight: "var(--typography-headline-large-font-weight)",
        }],
        "headline-medium": ["var(--typography-headline-medium-font-size)", {
          lineHeight: "var(--typography-headline-medium-line-height)",
          letterSpacing: "var(--typography-headline-medium-letter-spacing)",
          fontWeight: "var(--typography-headline-medium-font-weight)",
        }],
        "headline-small": ["var(--typography-headline-small-font-size)", {
          lineHeight: "var(--typography-headline-small-line-height)",
          letterSpacing: "var(--typography-headline-small-letter-spacing)",
          fontWeight: "var(--typography-headline-small-font-weight)",
        }],
        "title-large": ["var(--typography-title-large-font-size)", {
          lineHeight: "var(--typography-title-large-line-height)",
          letterSpacing: "var(--typography-title-large-letter-spacing)",
          fontWeight: "var(--typography-title-large-font-weight)",
        }],
        "title-medium": ["var(--typography-title-medium-font-size)", {
          lineHeight: "var(--typography-title-medium-line-height)",
          letterSpacing: "var(--typography-title-medium-letter-spacing)",
          fontWeight: "var(--typography-title-medium-font-weight)",
        }],
        "title-small": ["var(--typography-title-small-font-size)", {
          lineHeight: "var(--typography-title-small-line-height)",
          letterSpacing: "var(--typography-title-small-letter-spacing)",
          fontWeight: "var(--typography-title-small-font-weight)",
        }],
        "body-large": ["var(--typography-body-large-font-size)", {
          lineHeight: "var(--typography-body-large-line-height)",
          letterSpacing: "var(--typography-body-large-letter-spacing)",
          fontWeight: "var(--typography-body-large-font-weight)",
        }],
        "body-medium": ["var(--typography-body-medium-font-size)", {
          lineHeight: "var(--typography-body-medium-line-height)",
          letterSpacing: "var(--typography-body-medium-letter-spacing)",
          fontWeight: "var(--typography-body-medium-font-weight)",
        }],
        "body-small": ["var(--typography-body-small-font-size)", {
          lineHeight: "var(--typography-body-small-line-height)",
          letterSpacing: "var(--typography-body-small-letter-spacing)",
          fontWeight: "var(--typography-body-small-font-weight)",
        }],
        "label-large": ["var(--typography-label-large-font-size)", {
          lineHeight: "var(--typography-label-large-line-height)",
          letterSpacing: "var(--typography-label-large-letter-spacing)",
          fontWeight: "var(--typography-label-large-font-weight)",
        }],
        "label-medium": ["var(--typography-label-medium-font-size)", {
          lineHeight: "var(--typography-label-medium-line-height)",
          letterSpacing: "var(--typography-label-medium-letter-spacing)",
          fontWeight: "var(--typography-label-medium-font-weight)",
        }],
        "label-small": ["var(--typography-label-small-font-size)", {
          lineHeight: "var(--typography-label-small-line-height)",
          letterSpacing: "var(--typography-label-small-letter-spacing)",
          fontWeight: "var(--typography-label-small-font-weight)",
        }],
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      spacing: {
        "space-0": "var(--space-0)",
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-7": "var(--space-7)",
        "space-8": "var(--space-8)",
        "space-9": "var(--space-9)",
        "space-10": "var(--space-10)",
        "space-11": "var(--space-11)",
      },
    },
  },
  plugins: [],
};
export default config;
