interface TermsTabProps {
  isScrolled?: boolean;
}

export function TermsTab({ isScrolled = false }: TermsTabProps) {
  return (
    <div className="animate-in fade-in duration-300 pb-12 relative w-full">
      <div className={`sticky top-[-24px] lg:top-[-32px] z-40 -mx-10 px-10 lg:-mx-14 lg:px-14 pt-6 lg:pt-8 pb-4 mb-6 transition-all duration-500 ease-in-out ${isScrolled ? 'bg-white/80 backdrop-blur-md shadow-[0_2px_10px_rgba(0,0,0,0.02)]' : 'bg-[#f9fafb]'}`}>
        <div className="max-w-4xl">
          <div className="flex flex-col">
            <div className="flex items-center justify-between">
              <h2 className={`font-bold text-[var(--color-on-surface)] tracking-tight transition-all duration-500 ease-in-out origin-left ${isScrolled ? 'text-[clamp(1.125rem,2vw,1.25rem)] scale-95' : 'text-[clamp(1.5rem,3vw+0.5rem,1.875rem)] scale-100'}`}>Terms of Service</h2>
            </div>
            
            <div className={`grid transition-all duration-500 ease-in-out ${isScrolled ? 'grid-rows-[0fr] opacity-0 mb-0' : 'grid-rows-[1fr] opacity-100 mt-2'}`}>
              <div className="overflow-hidden">
                <p className="text-[0.875rem] font-medium text-[var(--color-on-surface-variant)] opacity-70">Last updated: June 11, 2026</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col md:flex-row gap-12 max-w-4xl">
        <div className="flex-1 max-w-2xl prose prose-slate">

          <div className="space-y-10 text-[0.9375rem] text-[var(--color-on-surface-variant)] leading-relaxed">
            <p>
              Welcome to PlateUp. These Terms of Service ("Terms") govern your use of the PlateUp application and website. By accessing or using our services, you agree to be bound by these Terms and our Privacy Policy.
            </p>

            <section id="acceptance">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">1. Acceptance of Terms</h3>
              <p>By creating an account, accessing, or using PlateUp, you agree to comply with and be bound by these Terms. If you do not agree to these Terms, you may not use our services.</p>
            </section>

            <section id="user-accounts">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">2. User Accounts</h3>
              <p className="mb-4">To use most features of PlateUp, you must register for an account. You agree to:</p>
              <ul className="list-disc pl-5 space-y-2 mb-4">
                <li>Provide accurate, current, and complete account information.</li>
                <li>Maintain the security of your password and accept all risks of unauthorized access to your account.</li>
                <li>Promptly notify us if you discover or suspect any security breaches related to your account.</li>
                <li>Verify your email address before gaining full access to protected functionality.</li>
              </ul>
            </section>

            <section id="acceptable-use">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">3. Acceptable Use</h3>
              <p className="mb-4">You agree not to use PlateUp for any unlawful or prohibited purpose. You must not:</p>
              <ul className="list-disc pl-5 space-y-2 mb-4">
                <li>Attempt to bypass or circumvent any rate limits or security features.</li>
                <li>Use the service to generate malicious, offensive, or inappropriate content.</li>
                <li>Reverse engineer or attempt to extract the source code of the application.</li>
                <li>Interfere with or disrupt the integrity or performance of the service.</li>
              </ul>
            </section>

            <section id="ai-disclaimer">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">4. AI-Generated Recommendations Disclaimer</h3>
              <p className="mb-4">PlateUp uses artificial intelligence (AI) to generate meal plans, shopping lists, ingredient recommendations, and budget assessments.</p>
              <p className="mb-4">While we strive to provide helpful and practical recommendations, all meal plans, shopping lists, ingredient suggestions, and budget assessments are estimates only and may not reflect actual market conditions.</p>
              <p className="mb-4">Food prices may vary based on location, season, availability, inflation, vendor pricing, and other factors beyond PlateUp's control.</p>
              <p className="mb-4">Users should independently verify ingredient availability, pricing, nutritional information, and purchasing decisions before relying on any recommendation generated by PlateUp.</p>
              <p className="mb-4">PlateUp does not guarantee the accuracy, completeness, affordability, or suitability of any AI-generated recommendation and should not be considered financial, nutritional, dietary, medical, or professional advice.</p>
              <p>By using PlateUp, you acknowledge that AI-generated outputs are provided for informational and planning purposes only.</p>
            </section>

            <section id="service-availability">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">5. Service Availability</h3>
              <p>We reserve the right to modify, suspend, or discontinue PlateUp (or any part of it) at any time, with or without notice. We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the service.</p>
            </section>

            <section id="intellectual-property">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">6. Intellectual Property</h3>
              <p>The PlateUp application, including its original content, design, logo, and features, is owned by PlateUp and is protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
            </section>

            <section id="limitation-of-liability">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">7. Limitation of Liability</h3>
              <p>In no event shall PlateUp, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>
            </section>

            <section id="contact">
              <h3 className="text-[1.25rem] font-bold text-[var(--color-on-surface)] mb-4">8. Contact Information</h3>
              <p>If you have any questions about these Terms, please contact us at:</p>
              <p className="mt-2 font-medium text-[var(--color-primary)]">legal@plateup.com</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
