import { validateIngredients } from '../lib/ai-sanitizer';
import { validateShoppingQuantities } from '../lib/quantity-validator';
import { calculateSafeEstimatedCost } from '../lib/meal-pipeline';

function runTest() {
  console.log("=== RUNNING AUTO-ADD TEST ===");

  // Scenario: Budget is 25,000 NGN.
  const budget = 25000;
  // User pantry has only: rice, beans, eggs, oil, onions
  const pantry = "rice, beans, eggs, oil, onions";

  // Meal plan generated by AI uses "Garri" (in Eba on Tuesday)
  const mealPlan = [
    {
      day: "Monday",
      breakfast: "Rice and eggs",
      lunch: "Beans",
      dinner: "Rice and Stew",
      primaryIngredientsUsed: ["rice", "eggs", "oil", "onions"]
    },
    {
      day: "Tuesday",
      breakfast: "Bread", // Bread is also missing!
      lunch: "Eba and soup", // Garri is missing!
      dinner: "Rice",
      primaryIngredientsUsed: ["bread", "garri", "oil", "rice"]
    }
  ];

  // Shopping list generated by AI contains only "bread" and "rice"
  // Note that "garri" is missing from both pantry and shopping list!
  const shoppingList = [
    { item: "bread", quantity: "1 loaf" },
    { item: "rice", quantity: "2 De-ricas" }
  ];

  console.log("Initial shopping list:", JSON.stringify(shoppingList));

  // 1. Run validateIngredients to detect and auto-add missing ingredients
  validateIngredients(pantry, shoppingList, mealPlan);

  console.log("After validateIngredients:", JSON.stringify(shoppingList));

  // Verify that both "bread" and "garri" are in the shopping list
  const itemsInList = shoppingList.map(s => s.item.toLowerCase());
  const hasGarri = itemsInList.includes("garri");
  const hasBread = itemsInList.includes("bread");

  console.log(`Has Garri: ${hasGarri}`);
  console.log(`Has Bread: ${hasBread}`);

  // 2. Validate quantities
  validateShoppingQuantities(shoppingList, mealPlan, 2);
  console.log("After quantity scaling:", JSON.stringify(shoppingList));

  // 3. Recalculate cost
  const rawAiEstimatedCost = 15000;
  const recalculatedCost = calculateSafeEstimatedCost(shoppingList, rawAiEstimatedCost);
  console.log(`Recalculated Cost: ₦${recalculatedCost}`);

  // Check budget feasibility
  const isOverBudget = recalculatedCost > budget;
  console.log(`Is Over Budget (exceeds ${budget}): ${isOverBudget}`);

  if (hasGarri && !isOverBudget) {
    console.log("SUCCESS: Auto-addition and cost recalculation completed without failing!");
  } else {
    console.log("FAILURE: Verification failed.");
  }
}

runTest();
